version: '3.8'

services:
  telegram-bot:
    build: .
    environment:
      - BOT_TOKEN=7767366013:AAH7xhl49t-_DuiQjneqRG33U1dKcI0z7Zk
      - API_URL_TEMPLATE=https://no-permanent-like-api.vercel.app/like?uid={uid}&server_name={region}
      
      - WEBHOOK_URL=https://no-permanent-like-onrender.com/
      - PORT=5000
    ports:
      - "5000:5000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M